image: node:18

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Firebase Hosting
          caches:
            - node
          script:
            - npm install
            - npm run build
